name: Test Secret

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mask Secret
        run: echo "::add-mask::${{ secrets.REALLYBAD }}"

      - name: Print Secret (Safely)
        run: echo "My secret is set but hidden in logs."
