name: Test Secret

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if Secret is Set
        run: |
          if [ -z "${{ secrets.REALLYBAD }}" ]; then
            echo "❌ Secret is NOT set!"
            exit 1
          else
            echo "✅ Secret is set."
          fi
